#!/bin/bash

if [ x$1 = "xclean" ]; then
  echo Cleaning
  echo
  cd externals
  cd wiringPi
  make clean
  cd ../gpio
  make clean
  cd ../examples
  make clean
  cd ..

  cd drive
  make clean
  cd ..

else
  echo tortoise Build script - please wait...
  cd externals
  unzip wiringPi.zip -d ./wiringPi
  echo building wiringpi
  cd wiringPi/wiringPi
  make 
  sudo make install
  cd ../gpio
  make
  sudo make install
  cd ../examples
  make
  cd ../../../

  echo build tortoise drive code
  cd drive
  make
  cd ../
fi

echo
echo Build Script Complete.
