#!/bin/bash

echo "drive.c test script..."
./drive -f 0.05
./drive -b 0.05
./drive -l 0.5
./drive -r 0.5
./drive -f 0.05
./drive -b 0.05
./drive --left 0.6
./drive --right 0.6
./drive --forward 0.05
./drive --backward 0.05
